
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient()
public class InsulinaService extends Service
{
    private QName myQName;
    private String portName;

    public InsulinaService(URL wsdlLocation, QName metadata, String portName)
    {
        super(wsdlLocation, metadata);
        this.myQName = metadata;
        this.portName = portName;
    }

    @WebEndpoint(name = "InsulinDoseCalculatorPort")
    public Insulina getInsulinaPort() {
        return super.getPort(new QName(myQName.getNamespaceURI(), this.portName + "Port"), Insulina.class);
    }

    @WebEndpoint(name = "InsulinDoseCalculatorPort")
    public Insulina getInsulinaPort(WebServiceFeature... features) {
        return super.getPort(new QName(myQName.getNamespaceURI(), this.portName +"Port"), Insulina.class, features);
    }
}
